### ISSUE TITLE
RFP - cyberghost-vpn

### ISSUE THREAD

**Issue by AnthoFor** [chocolatey-community/chocolatey-package-requests#1495] opened 2024-03-08 10:41 UTC
## Checklist

- [x] The package I am requesting does not already exist on https://community.chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.cyberghostvpn.com/
Direct download URL for the software / installer : https://download.cyberghostvpn.com/windows/CyberGhostVPNSetup.exe
Software summary / short description: Well Known VPN.

**Comment by pauby** [comment] 2024-03-08 11:59
This is a duplicate of #708

**Closed by pauby** 2024-03-08 11:59 UTC
Labels: Status: Triage
