### ISSUE TITLE
RFP - bluestacks-5

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-package-requests#996] opened 2021-05-22 13:40 UTC
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.bluestacks.com/
Direct download URL for the software / installer : https://cloud.bluestacks.com/api/getdownloadnow?platform=win&win_version=10&mac_version=&client_uuid=211e5332-5767-4103-9e68-e0a8434df476&app_pkg=&platform_cloud=%257B%2522description%2522%253A%2522Firefox%252088.0%2520on%2520Windows%252010%252064-bit%2522%252C%2522layout%2522%253A%2522Gecko%2522%252C%2522manufacturer%2522%253Anull%252C%2522name%2522%253A%2522Firefox%2522%252C%2522prerelease%2522%253Anull%252C%2522product%2522%253Anull%252C%2522ua%2522%253A%2522Mozilla%252F5.0%2520(Windows%2520NT%252010.0%253B%2520Win64%253B%2520x64%253B%2520rv%253A88.0)%2520Gecko%252F20100101%2520Firefox%252F88.0%2522%252C%2522version%2522%253A%252288.0%2522%252C%2522os%2522%253A%257B%2522architecture%2522%253A64%252C%2522family%2522%253A%2522Windows%2522%252C%2522version%2522%253A%252210%2522%257D%257D&preferred_lang=en&utm_source=&utm_medium=&gaCookie=&gclid=&clickid=&msclkid=&affiliateId=&offerId=&transaction_id=&aff_sub=&first_landing_page=&referrer=&download_page_referrer=&utm_campaign=homepage-dl-button-en&exit_utm_campaign=homepage-dl-button-en&incompatible=false&bluestacks_version=bs5
Software summary / short description: BlueStacks is an American technology company known for the BlueStacks App Player and other cloud-based cross-platform products. The BlueStacks App Player is designed to enable Android applications to run on PCs running Microsoft Windows and Apple's macOS. The company was founded in 2009 by Jay Vaishnav, Suman Saraf, and Rosen Sharma, former CTO at McAfee and a board member of Cloud.com.

**Comment by pauby** [comment] 2022-12-02 08:31
This is a duplicate of #358

**Closed by pauby** 2022-12-02 08:31 UTC
Labels: Duplicate
