### ISSUE TITLE
RFM - git-flow-hooks

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey-community/chocolatey-package-requests#548] opened 2019-02-15 16:52 UTC
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/git-flow-hooks
Package source URL: https://github.com/jaspernbrouwer/git-flow-hooks

**Comment by chtof** [comment] 2019-10-09 11:43
The owner is now @boubou so it seems this issue can be closed.

**Comment by AdmiringWorm** [comment] 2019-10-23 11:51
@chtof he may be the owner, but there haven't been an updated version submitted yet. So closing the issue is not valid yet

**Comment by chtof** [comment] 2019-10-23 19:37
@AdmiringWorm Ok, I will be more precise next time! So:
- Actual maintainer requested to pass the package to someone else and @boubou has asked and is now the new maintainer.
- The previous version was submitted in 2016 and there is no new version (abandonned ?).

So, with these new information, I request again to close this issue (new maintainer and no new version for about 3 years and latest version is available).

**Comment by pauby** [comment] 2019-10-25 15:38
@chtof This is not a normal RFM in that a new maintainer is usually requested because a package is out of date _and_ there is a new version available (which is why it's noticed that the current maintainer is not maintaining the package) which is where @AdmiringWorm is coming from.

Given this request is unusual I'm going to go ahead and close it now.

**Closed by pauby** 2019-10-25 15:38 UTC
