### ISSUE TITLE
RFP - AMD Radeon Software

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#831] opened 2020-06-19 01:41 UTC
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.amd.com/en/technologies/radeon-software

Direct download URL for the software / installer : 
https://drivers.amd.com/drivers/beta/win10-radeon-software-adrenalin-2020-edition-20.5.1-june10.exe

Software summary / short description: 
AMD Radeon Software Adrenalin 2020 Edition 20.5.1 installation package. Made by AMD.

**Comment by AdmiringWorm** [comment] 2020-06-19 15:16
Duplicate of #681

**Closed by AdmiringWorm** 2020-06-19 15:16 UTC
Labels: Status: Available For Maintainer(s)
