### ISSUE TITLE
RFP - citra

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1028] opened 2021-07-04 10:41 UTC
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://citra-emu.org/download/#
Direct download URL for the software / installer : https://github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-windows.exe
Software summary / short description:
Nintendo 3ds emulator

**Comment by TheCakeIsNaOH** [comment] 2021-10-01 15:00
Duplicate of #1000

**Closed by TheCakeIsNaOH** 2021-10-01 15:00 UTC
Labels: Status: Triage
