### ISSUE TITLE
RFM - Octave

### ISSUE THREAD

**Issue by Foadsf** [chocolatey-community/chocolatey-package-requests#487] opened 2018-12-14 10:44 UTC
The [portable version of Octave](https://chocolatey.org/packages/octave.portable) is updated, however [the main one](https://chocolatey.org/packages/Octave) is still way behind. I left [a requested for update](http://disq.us/p/1wxnj6v) while ago still got no respond.

**Comment by pauby** [comment] 2018-12-14 10:47
@Foadsf Can you contact the maintainers using the 'Contact Maintainers' link on the package page?

**Comment by Foadsf** [comment] 2018-12-14 10:56
@pauby I have already done that. no response so far :(

**Comment by pauby** [comment] 2018-12-14 11:16
@Foadsf How long ago did you contact them?

**Comment by Foadsf** [comment] 2018-12-14 11:20
@pauby Informed Chocolatey guys on twitter a couple of month ago. Left the comment on Disqus one month ago, contacted the developers via the form 5 days ago again.

**Comment by chtof** [comment] 2019-04-28 13:26
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated package ready to be pushed:
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/octave
  - **https://github.com/chtof/chocolatey-packages/tree/master/automatic/octave.install** -> For his second one, I have an issue to published:

> cpush octave.install.5.1.0.nupkg
Chocolatey v0.10.14-beta-7-gb30427d
Attempting to push octave.install.5.1.0.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.

However, octave.install doesn't exist on Chocolatey and the size of the package is about 10 KB.

**Comment by chtof** [comment] 2019-05-04 14:55
Status: **Review**
- https://chocolatey.org/packages/Octave/5.1.0
- https://chocolatey.org/packages/Octave.install/5.1.0

**Comment by chtof** [comment] 2019-05-05 19:06
Well, I have a strange issue with octave.install.

- The installation works properly manually with the graphical installer.
- In silent mode, the installation hangs at the end of installation (see below) and it never finish (but Octave is installed as I can launch Octave). Same issue when using a chocolatey-test-environment (Vagrant/VirtualBox).
- So, I have scripted the installation with the graphical installer with autohotkey and also, the installation hangs at the end of the installation (but Octave is installed as I can launch Octave).
So, it seems to be an issue using the command-line to install the software.
Do you have had already a such issue? Or any idea?
[Github Repository of this package](https://github.com/chtof/chocolatey-packages/tree/master/automatic/octave.install)

```
(...)
Hashes match.
Command ['C:\ProgramData\chocolatey\helpers\..\tools\checksum.exe' -c="9F80C37BAF041BD741C2660E7E5E12AFBD19DAAB7E59AABA96288E630282122B" -t="sha256" -f="C:\*****\Temp\chocolatey_cache\octave.install\5.1.0\octave-5.1.0-w64-installer.exe"] exited with '0'.
Running Install-ChocolateyInstallPackage -packageName 'octave.install' -fileType 'exe' -silentArgs '' -file 'C:\*****\Temp\chocolatey_cache\octave.install\5.1.0\octave-5.1.0-w64-installer.exe' -validExitCodes '0' -useOnlyPackageSilentArguments 'False'
Running Get-ProcessorBits -compare '32'
Installing octave.install...
Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\*****\Temp\chocolatey_cache\octave.install\5.1.0' -statements ' ' -exeToRun 'C:\*****\Temp\chocolatey_cache\octave.install\5.1.0\octave-5.1.0-w64-installer.exe'
Test-ProcessAdminRights: returning True
Elevating permissions and running ["C:\*****\Temp\chocolatey_cache\octave.install\5.1.0\octave-5.1.0-w64-installer.exe"  ]. This may take a while, depending on the statements.
```

**Comment by gep13** [comment] 2019-05-08 09:18
@chtof I got to exactly the same point when I tried to package up this application.  It was the topic of a live streaming session that I did here:

https://www.youtube.com/watch?v=aecDukZETUE

On how to help with package maintenance.  My suggestion would be to reach out to the creators of the application/installer, to see if they are aware of anything.

**Comment by chtof** [comment] 2019-05-08 15:04
_If you need help using Octave, you have many options, from reading the Octave manual, asking for help on the mailing lists, chatting online with other Octave users, or paying for commercial support._
So, I have sent a message to the mailing-list: https://lists.gnu.org/archive/html/help-octave/2019-05/msg00037.html

**Comment by gep13** [comment] 2019-05-09 07:15
@chtof It will be interesting to see if an answer is received there.  If I could ask that you keep me posted, I would appreciate it.

**Comment by chtof** [comment] 2019-05-11 17:21
@gep13 https://lists.gnu.org/archive/html/help-octave/2019-05/msg00057.html
I have not yet answered. My thoughs: 
- Problem is this issue doesn't occurs outside chocolatey (because octave-5.1.0-w64-installer.exe /S is run immediately as background process).
- So, maybe we should inspect files in https://hg.octave.org/mxe-octave/file/tip/installer-files (launch each of them in command-line)? I have no idea of the kind of script who can hangs a Chocolatey install script.

**Comment by AdmiringWorm** [comment] 2019-05-11 17:59
@chtof actually, it is reproducable outside of chocolatey.
Just tested the following in powershell
```powershell
start-process -FilePath .\octave.exe -ArgumentList "/S" -Wait
```

been running for 10-15 minutes now, and hasn't let go yet.

**Comment by chtof** [comment] 2019-05-11 20:51
@gep13 Ok, but for octave developers, "it will be probably not a normal way
to install octave". Either Chocolatey should be able to install a such
package or octave should have an installer compatible with a package
manager as Chocolatey? That is the question I think.
Also, I laughed a lot when I have seen the Youtube video. You was very
unlucky to have choosen a problematic package for your demo but in the same
time, it was really interesting to see what can be checked in a such
situation!

Le sam. 11 mai 2019 à 19:59, Kim J. Nordmo <notifications@github.com> a
écrit :

**Comment by gep13** [comment] 2019-05-12 10:02
@chtof I actually knew ahead of time that this package was causing issues. I was hoping in the back of my mind that it would be “fixed” in the new release and it would “just” work, but I was also concerned that it wouldn’t.

Since this is reproducible outside of Chocolatey, I think we have something to go back to the Octave developers with. Although, as they point out, maybe best to simply stick with the portable version?

@AdmiringWorm thanks for checking that!

I suspect they are spawning some sort of background process that isn’t returning to the original caller, which results in the problem that we are seeing.

**Comment by chtof** [comment] 2019-05-30 11:39
@gep13 After some searchs, it's due to a call to `%MSYSDIR%\bin\bash.exe --login -c echo` in the post-install.bat script.
I have yet to check if there are side-effects to exclude this line or maybe to add the use of a command like startcmd to launch this "bash.exe" call.

@AdmiringWorm

**Comment by chtof** [comment] 2019-05-30 12:30
But unfortunately, I can't change a file during an installation... So I have just updated the case to know if this call is really needed or if it can be launched in another way (with startcmd for example).

@gep13 @AdmiringWorm

**Comment by chtof** [comment] 2019-05-30 13:25
Status: **Review**
- https://chocolatey.org/packages/octave
- https://chocolatey.org/packages/octave.install

Following my previous post, using autohotkey, a file can be changed as soon as an installation starts :-) ! So it works !
See https://github.com/chtof/chocolatey-packages/blob/master/automatic/octave.install/tools/chocolateyinstall.ahk
@gep13 @AdmiringWorm 

Already approved:
- https://chocolatey.org/packages/octave.portable/5.1.0

**Comment by gep13** [comment] 2019-05-30 16:20
@chtof great work!

Did you get an official reply on whether this can be worked around like this? Any side effects?

Also, why the need for the verification.txt in the package?

**Comment by chtof** [comment] 2019-05-30 16:30
@gep13

I have only sent a new post about it on the Octave mailing-list today: https://lists.gnu.org/archive/html/help-octave/2019-05/msg00221.html
In fact, I have just seen I am not maintainer for octave.portable so it's not my fault ;-)

**Comment by pauby** [comment] 2019-05-31 08:56
@chtof It might be worth reaching out to the maintainer of the octave.portable package to see if they would be happy for you to take over that package too. Makes sense to own all of them. That assumes you want to of course 😄 

octave and octave.install are approved.

**Closed** 2019-06-14 17:27 UTC
Labels: Status: Published
