### ISSUE TITLE
RFM - Growl

### ISSUE THREAD

**Issue by plroebuck** [chocolatey-community/chocolatey-package-requests#454] opened 2018-10-19 12:18 UTC
[https://chocolatey.org/packages/Growl](https://chocolatey.org/packages/Growl)

**Comment by pauby** [comment] 2018-10-19 13:43
@plroebuck Have you followed the Package Triage Process and contacted the maintainers in the first instance?

**Comment by plroebuck** [comment] 2018-10-19 14:01
Attempted contact with [both via GitHub](https://github.com/mochajs/mocha/issues/3483#issuecomment-429853137). No response from either.

From package homepage comments, it's been broken for over two years now.

**Comment by pauby** [comment] 2018-10-19 14:56
Can you use the 'Contact Maintainers' link on the package page?

**Comment by plroebuck** [comment] 2018-10-19 19:09
Done.
But if they haven't fixed the problems in several years, it's kinda obviously unmaintained.

**Comment by plroebuck** [comment] 2018-11-01 21:35
Well?

**Comment by pauby** [comment] 2018-11-01 22:15
@plroebuck theres a question mark at the end of that. But no question.

**Comment by plroebuck** [comment] 2018-11-02 10:00
It's been 2 calendar weeks. Have the maintainer's responded to you? I never heard back from anyone.

What are next steps?

**Comment by pauby** [comment] 2018-11-02 10:59
@plroebuck See the the [first message I sent you](https://github.com/chocolatey/chocolatey-package-requests/issues/454#issuecomment-431367641) and go through the process. 

For brevity 1) the maintainers respond to your message - we're not involved, and 2) if you have the skills, or want to learn the skills to maintain the package, use the 'Contact Site Admins' link on the package page, ask to become the maintainer, and reference this GitHub issue.

Can I also remind you the moderators are volunteers. Responding to an issue with 'Well?' will generally get no response. I have you the benefit of doubt but it's generally considered rude.

**Comment by plroebuck** [comment] 2018-11-02 12:07
> @plroebuck See the the [first message I sent you](https://github.com/chocolatey/chocolatey-package-requests/issues/454#issuecomment-431367641) and go through the process.
> 
> For brevity 1) the maintainers respond to your message - we're not involved, and 2) if you have the skills, or want to learn the skills to maintain the package, use the 'Contact Site Admins' link on the package page, ask to become the maintainer, and reference this GitHub issue.
> 
> Can I also remind you the moderators are volunteers. Responding to an issue with 'Well?' will generally get no response. I gave you the benefit of doubt but it's generally considered rude.

No rudeness intended at all. Do *lots* of support myself for [Mocha](https://mochajs.org/). Was in reference to your process (but then forgot to quote it while hurrying):
> If the maintainer(s) are unresponsive after a period of time **(determined by the admins)**, the package is considered abandoned.

**Comment by pauby** [comment] 2018-11-22 11:55
@plroebuck Did you receive a response from the maintainers? I'm assuming not by the comments above but I just want to be clear before moving forward.

**Comment by plroebuck** [comment] 2018-11-22 19:45
@pauby, no response.

**Comment by chtof** [comment] 2019-08-03 14:23
https://www.growlforwindows.com is unavailable for several years.
The installer is not embedded and so, the latest approved version fails.

What about to hide approved versions of this package and to close this issue?

**Comment by AdmiringWorm** [comment] 2019-08-03 14:59
@chtof the website works perfectly fine.
If it was unavailable previously is something I can't say anything about, but the page both opens and can be browsed.

**Comment by chtof** [comment] 2019-08-10 12:24
Strange, it doesn't work at home, in fact it works on my smartphone after disabling Wi-Fi...

**Comment by AdmiringWorm** [comment] 2019-08-10 14:08
sounds like your isp is either blocking the website, or the dns server used isn't resolving the domain name.

**Comment by chtof** [comment] 2019-08-17 19:30
At time when I write this post, the site is down https://www.isitdownrightnow.com/growlforwindows.com.html

**Comment by chtof** [comment] 2019-10-26 14:23
I didn't find an installer on https://www.growlforwindows.com. There is a "download" icon on the webpage but without link to download the installer! Someone can also check if he find an installer on the website? Thanks in advance!

**Comment by chtof** [comment] 2019-12-28 22:11
Could a moderator can check if there is an intaller on https://www.growlforwindows.com? And to close this issue if it's confirmed there is no available installer? Thank you.

**Comment by gep13** [comment] 2019-12-29 21:06
@chtof looks like the last available version is stored on the GitHub repository here:

https://github.com/briandunnington/growl-for-windows#growl-for-windows

Not sure why this isn't linked through from the growlforwindows website though.

**Comment by chtof** [comment] 2020-01-25 12:16
Status: **In progress**
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Latest version already available in Chocolatey and "Growl for Windows" seems to be no longer maintained.

**Comment by pauby** [comment] 2020-01-28 11:02
@chtof If 'Growl For Windows' is no longer maintained I'm unsure if we should still have this issue open?

**Comment by chtof** [comment] 2020-01-28 11:54
@pauby **Can be closed** as no longer maintened and latest version already available on Chocolatey.

**Closed** 2020-01-28 14:19 UTC
Labels: Not Request / Can't Implement / Exists / Invalid
