### ISSUE TITLE
RFP - Rockstar Games Launcher

### ISSUE THREAD

**Issue by EpsilonsQc** [chocolatey-community/chocolatey-package-requests#839] opened 2020-06-19 01:57 UTC
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://socialclub.rockstargames.com/rockstar-games-launcher

Direct download URL for the software / installer : 
https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe

Software summary / short description: 
Download and play the latest Rockstar Games PC titles. Made by Rockstar Games.

**Comment by chtof** [comment] 2020-07-25 11:32
Duplicate: https://github.com/chocolatey-community/chocolatey-package-requests/issues/714

**Comment by AdmiringWorm** [comment] 2020-07-25 15:35
Duplicate of #714

**Comment by AdmiringWorm** [comment] 2020-07-25 15:36
thanks @chtof must have missed that when opening this up for maintainers

**Closed by AdmiringWorm** 2020-07-25 15:35 UTC
Labels: Status: Available For Maintainer(s)
