### ISSUE TITLE
RFP - logitechgamingsoftware

### ISSUE THREAD

**Issue by dtantono** [chocolatey-community/chocolatey-package-requests#1090] opened 2021-11-03 08:17 UTC
Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :https://support.logi.com/hc/ja/articles/360024703714
Direct download URL for the software / installer : https://download01.logi.com/web/ftp/pub/techsupport/joystick/lgs510j_x64.exe
Software summary / short description:
additional app for configure game controller and wheels

**Comment by pauby** [comment] 2021-11-03 18:26
Is this different from https://community.chocolatey.org/packages/logitechgaming ?

**Comment by dtantono** [comment] 2021-11-04 00:04
the function is different

**Comment by jakublevy** [comment] 2021-12-28 08:29
International version: https://community.chocolatey.org/packages/logitechgaming5
Japanese version: https://community.chocolatey.org/packages/logicoolgaming5

Note that although it seems like version 5 of Logitech Gaming, it is actually very different software that supports different Logitech devices. It is not duplicate of already existing [logitechgaming](https://community.chocolatey.org/packages/logitechgaming) or [logicoolgaming](https://community.chocolatey.org/packages/logicoolgaming) package.

**Comment by jakublevy** [comment] 2022-02-03 06:16
Packages approved.

**Closed** 2022-02-03 15:45 UTC
Labels: Status: Published
