### ISSUE TITLE
RFP - devkitPro Updater

### ISSUE THREAD

**Issue by ketsuban** [chocolatey-community/chocolatey-package-requests#624] opened 2019-06-21 17:15 UTC
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://devkitpro.org/
Direct download URL for the software / installer: https://github.com/devkitPro/installer/releases/download/v3.0.3/devkitProUpdater-3.0.3.exe
Software summary / short description: devkitPro provide a number of GNU cross-compiler toolchains aimed at homebrew development for games consoles ranging from the Game Boy Advance to the Switch.

The Chocolatey package should allow the user to specify an alternative install folder (the default is `C:\devkitPro`) and enable or disable toolchains via commandline flags, and disable adding its folders to the user's PATH. It should *not* allow the user to prevent the creation of environment variables such as `DEVKITPRO` and `DEVKITARM`; these are needed to use the Makefiles the toolchains provide for homebrew developers.

**Comment by chtof** [comment] 2019-08-15 17:24
Status: **Review**
https://chocolatey.org/packages/devkitpro

**Comment by AdmiringWorm** [comment] 2019-10-02 23:09
@chtof I see your package have been rejected (due to not being fixed after 45 days), are you still planning on going back to the package? Or should we open it up for new maintainers?

**Comment by chtof** [comment] 2019-10-03 01:17
Hi @AdmiringWorm ,
The package is pretty finished ("99,9%"). There is only something special to handle and it's rather difficult. To explain that:
- Devkitpro installer works well outside Chocolatey (when not called by PowerShell).
- Devkitpro installer call a windows batch file, calling "`bash --login`" commands and it doesn't/can't return an error code, so Powershell never knows when it should continue.
- I had treated a such package in the past named "Octave", where I had to use AutoHotKey to modify batch file as soon as this file appears (for "Octave", I have just removed the problematic line as it was not needed). But here, the additionnal difficulty is to know how to modify the batch file as these "bash login" commands are really needed contrarily to "Octave" package.
- The source code for the package is available here: https://github.com/chtof/chocolatey-packages/tree/master/automatic/devkitpro
- I have attached the problematic file (there are 2 files but there are pretty identicals).
[msys2.zip](https://github.com/chocolatey-community/chocolatey-package-requests/files/3684056/msys2.zip)
  - In these files, you will find several "`/usr/bin/bash --login`" who are not really "compatible" to be called with PowerShell waiting a return code to continue. Any help is welcome.

**Comment by AdmiringWorm** [comment] 2019-10-03 01:27
I see, it is unfortunate that it is such a problematic package.
I would love to help, but I honestly do not have any idea how to get around the issue.

I think the best bet would be to try getting a dialog with the developers of the installer, maybe they know how (or can implement something in the installer) so the install at least won't be hanging.

**Comment by chtof** [comment] 2019-10-03 02:07
I have just worked again a few minutes and I remember anything else. The root cause is the same but in another file. I think the NSIS installer logically uses https://github.com/devkitPro/installer/blob/master/nsis/devkitPro.nsi and this devkitPro.nsi file contains:  `ExecWait '"$INSTDIR\msys2\usr\bin\bash.exe" --login -c exit'`
I will see if I am able to build a new NSIS installer to check is it is the precise root cause. And if it is the case, you are true, the last solution will be to have a dialog with the developers. Thank you.

**Comment by chtof** [comment] 2019-10-03 19:02
Issue opened on [devkitPro GitHub tracker](https://github.com/devkitPro/installer/issues/19).

**Comment by fincs** [comment] 2019-10-03 19:05
Please see https://github.com/devkitPro/installer/issues/19#issuecomment-538081743

Alternative installation methods other than the officially supported devkitPro pacman method are not supported, and we are unable to provide instructions or guidance on how to bypass it.

**Comment by chtof** [comment] 2019-10-03 19:23
@fincs 
@AdmiringWorm It seems they are not interested to an easy way to promote and to install devkitPro, requesting a little effort to find an alternative to one command-line "bash --login". So, what about to close this case as _Can't implement_ ? (Not Request / Can't Implement / Exists / Invalid label).

**Comment by chtof** [comment] 2019-10-03 19:26
And also for @ketsuban; 

_"devkitPro is not the name of any piece of software. It's the name of the organization which produces and provides a bunch of tools and libraries for homebrew development."_
Source: https://github.com/devkitPro/installer/issues/19#issuecomment-538081743

**Comment by fincs** [comment] 2019-10-03 19:44
>  It seems they are not interested to an easy way to promote and to install devkitPro

This is a very incorrect statement. First of all, as pointed out by my comment (which you also quoted), devkitPro is not the name of a piece of software; it's the name of an organization.

We have evolved our software distribution system over the course of 15+ years to be as simple and straightforward to install and maintain. Third parties trying to redistribute or repackage devkitPro software have caused numerous support issues and grief, and we would very much rather ask anyone involved here to please reconsider and instead link to our official guides and support pages in order to set up a proper toolchain installation.

**Comment by ketsuban** [comment] 2019-10-03 19:54
@chtof 

I am well aware. I referred to "devkitPro Updater" (the name of this piece of software) and said "devkitPro provide a number of GNU cross-compiler toolchains" (which they do).

**Comment by chtof** [comment] 2019-10-03 20:30
> > It seems they are not interested to an easy way to promote and to install devkitPro
> 
> This is a very incorrect statement. First of all, as pointed out by my comment (which you also quoted), devkitPro is not the name of a piece of software; it's the name of an organization.
> 
> We have evolved our software distribution system over the course of 15+ years to be as simple and straightforward to install and maintain. Third parties trying to redistribute or repackage devkitPro software have caused numerous support issues and grief, and we would very much rather ask anyone involved here to please reconsider and instead link to our official guides and support pages in order to set up a proper toolchain installation.

@fincs Ok, my understanding is you have had numerous issues with third parties to redistribute or repackage devkitPro, I can understand that after having seen all commands launched by the installer.
You said you support only the installation with pacman method but on https://devkitpro.org/wiki/Getting_Started , you also provide an installer so we can think this installation method is also supported.  **Just to be sure there is no misunderstanding, Chocolatey doesn't rebuild devkitPro and/or the installer :** Using Powershell, a Chocolatey package launch simply devkitProUpdater-3.0.3.exe using silent args, the installer is called with a "Start-Process -Wait" Powershell command to know when the installation is correctly finished. And after some tests, the failure is due to an only line in *.nsi file of the installer provided on devkitpro website.
And also I can understand you doesn't want to support issues due to another installation method but when a third party uses your installer, the installation is the same comparated to execute directly the installer (excepted of course when a particular command does not return a return signal as bash --login).

**Comment by WinterMute** [comment] 2019-10-03 20:45
@chtof your understanding is wrong and we don't require the existence of an alternative package we can't and won't support. 

Bootstrapping msys2 and the package management system we use to maintain our packages (currently around 160 of them) is not compatible with Powershell and we'd really rather you didn't attempt to shoehorn this into a packaging system we have no intention of using or supporting.

**Comment by fincs** [comment] 2019-10-03 20:45
> Chocolatey doesn't rebuild devkitPro and/or the installer

devkitPro cannot be "rebuilt". devkitPro is an organization, not a piece of software. This is akin to trying to install Microsoft or Adobe without specifying which product.

Regardless of what Chocolatey does, we do not wish for third parties to redistribute or otherwise interfere with the supported installation methods for our software. devkitProUpdater is essentially a single use tool we provide directly to Windows end users as a courtesy, in order to set up a msys2 installation with the devkitPro repositories pre-configured. It makes no sense for Chocolatey to redistribute or repackage said tool.

**Comment by chtof** [comment] 2019-10-03 21:00
@WinterMute Thanks for this additionnal information.
@fincs About _"It makes no sense for Chocolatey to redistribute or repackage said tool._". Chocolatey is a method to install and upgrade easily software. It allows to install easily a software, for example "choco install firefox" to install firefox and "choco update all" to update all software installed by Chocolatey. It's easier than having to search "devkitpro" on Google, click on the url matching devkitpro, click on download link, download the software, click on the installer, wait the end of the installation and check regularly if a new version has been released and to repeat these same tasks.

**Comment by fincs** [comment] 2019-10-03 21:03
You're not listening at all. devkitProUpdater is not updated when we publish new software. Our distribution channel is pacman, and `pacman -Syu` is used to update our software. devkitProUpdater is just a helper tool that is only used at the beginning of the lifetime of a toolchain installation, and there's no reason why Chocolatey would want to do anything with it, let alone upgrade it (which will accomplish nothing on an already existing toolchain installation).

**Comment by chtof** [comment] 2019-10-04 00:53
@fincs This issue is related to "devkitPro Updater" and no related to "devkitPro" itself. My other issue was opened in the **installer** ("helper tool") repository of devkitPro.
- Yes, devkitPro use pacman to update itself and it's not for devkitPro we want to create an installer but for devkitProUpdater.
- devkitProUpdater has had several releases until last year (Version 3.0.3) and maybe or not, other versions would be released. Chocolatey package manager can update software, but before that, for a Chocolatey user, it's user-friendly to just have to type "choco install devkitproupdater". But a "bash --login" instruction in the installer doesn't allow to do that. The devkitPro installer has been build with an installer software named "NSIS". A [".nsi"](https://github.com/devkitPro/installer/blob/master/nsis/devkitPro.nsi) script contains all the information to install a software (msys2 and pacman in your case). The issue is inside this script which it uses to build the installer (devkitProUpdater-3.0.3.exe) with NSIS.

**Comment by WinterMute** [comment] 2019-10-04 09:08
> @fincs This issue is related to "devkitPro Updater" and no related to "devkitPro" itself. My other issue was opened in the **installer** ("helper tool") repository of devkitPro.
> 
> * Yes, devkitPro use pacman to update itself and it's not for devkitPro we want to create an installer but for devkitProUpdater.

And we don't want you to create an installer for devkitProUpdater. It makes no sense. devkitProUpdater is a one shot tool for bootstrapping our package manager which then installs and updates the packages we provide.  

Can you stop attempting to explain our own software to us. We know what it does, we know how it works and it cannot be managed by Chocolatey.

**Comment by pauby** [comment] 2019-10-05 04:06
@wintermute @fincs Chocolatey packages silently install the software on the computer. They don't rebuild, repackage and don't have to redistribute it (downloading and installing it at runtime). In effect it does what the end user would do when they download software but automates so that it ends up being silent.

There is a lot of miscommunication and clearly a misunderstanding or what Chocolatey can do and what it's goals are.

Having said that it's clear you don't want Chocolatey being used for it and that's up to you. @chtof I'm going to close this and marked as being blocked upstream for the time being.

**Closed by pauby** 2019-10-05 04:06 UTC
Labels: Status: In Progress
