### ISSUE TITLE
RFM - gamedownloader

### ISSUE THREAD

**Issue by dougmcdorman** [chocolatey-community/chocolatey-package-requests#1145] opened 2022-01-01 03:45 UTC
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gamedownloader
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2021-12-13
How the maintainer was contacted: email

**Comment by AdmiringWorm** [comment] 2022-02-09 02:35
Note that this request includes the packages gamedownloader.portable, and gamedownloader.install.

**Comment by tunisiano187** [comment] 2024-04-05 17:56
Hello,
This software hasn't been updated since 2014 and their website version 2018, so i don't think it worth it ;-)
Have a nice day.

**Comment by pauby** [comment] 2024-04-07 23:55
Confirmed no update since 2018. Unlikely this will be updated. Closing.

**Closed by pauby** 2024-04-07 23:55 UTC
Labels: Status: Available For Maintainer(s)
