### ISSUE TITLE
RFM - Moonlight-QT

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-package-requests#603] opened 2019-05-21 19:12 UTC
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/moonlight-qt
Package source URL: Was [here](https://github.com/tlm-2501/choco/) but is no longer there.

**Comment by chtof** [comment] 2019-05-24 13:41
Status: **In progress**
- **It seems moonlight-qt is a duplicate of moonlight. Probably better to keep moonlight-qt (as there are several ways to install it) so I will redirect moonlight to moonlight-qt **. Also I will renamed the updated packages (see below).
- Waiting to be added as maintainer (request already sent to Chocolatey contact-site admins).
- Updated packages ready to be published:
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/moonlight
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/moonlight.install
  - https://github.com/chtof/chocolatey-packages/tree/master/automatic/moonlight.portable

**Comment by AdmiringWorm** [comment] 2019-05-24 17:00
@chtof considering that the package moonlight never had an approved version (and was created after moonlight-qt), I would say that the moonlight is a duplicate of moonlight-qt instead.
Since a version of moonlight was never approved, it officially do not exist on the community repository.

As such, I would say to ignore that package, and instead just focus on moonlight-qt (and change the install/portable package id to be `moonlight-qt.install/portable`).

**Comment by chtof** [comment] 2019-05-27 18:13
Status: **Review**
- https://chocolatey.org/packages/moonlight-qt
- https://chocolatey.org/packages/moonlight-qt.portable
- Deprecation of https://chocolatey.org/packages/moonlight for moonlight-qt
- Deprecation of https://chocolatey.org/packages/moonlight.install for moonlight-qt.install
- Deprecation of https://chocolatey.org/packages/moonlight.portable for moonlight-qt.portable

Already approved:
- https://chocolatey.org/packages/moonlight-qt.install

**Comment by chtof** [comment] 2019-06-08 13:51
Status: **Published**
- https://chocolatey.org/packages/moonlight-qt
- https://chocolatey.org/packages/moonlight-qt.install
- https://chocolatey.org/packages/moonlight-qt.portable
- Deprecation of https://chocolatey.org/packages/moonlight for moonlight-qt
- Deprecation of https://chocolatey.org/packages/moonlight.install for moonlight-qt.install
- Deprecation of https://chocolatey.org/packages/moonlight.portable for moonlight-qt.portable

Can be closed.

**Closed** 2019-06-08 14:36 UTC
Labels: Status: Published
