### ISSUE TITLE
RFP - DjVu Converter

### ISSUE THREAD

**Issue by Kristinita** [chocolatey-community/chocolatey-package-requests#650] opened 2019-08-12 06:47 UTC
### 1. Checklist

- [x] The package I am requesting [**does not already exist**](https://chocolatey.org/packages?q=djvu%20converter) on **<https://chocolatey.org/packages>**;
- [x] [**There is no open issue for this package**](https://github.com/chocolatey-community/chocolatey-package-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+djvu+converter);
- [x] The issue title starts 'RFP — ';
- [x] The download URL is public and not locked behind a paywall / login;

### 2. Package Details

+ Software project URL: **<http://www.djvuconverter.com/index.html>**;
+ Direct download URL for installer: **<http://www.softsea.com/download/DjVu-Converter.html>**;
+ Software summary/short description: free convert DjVu to another formats — PDF, EPUB, TIFF, JPG/JPEG and PNG:

    ![DjVu Converter](https://i.imgur.com/7Ote2bu.png)

Thanks.

**Comment by chtof** [comment] 2019-08-14 18:12
Status: **Review**
https://chocolatey.org/packages/djvu-converter

**Comment by pauby** [comment] 2020-01-28 10:54
@chtof The package submitted has been rejected within the grace period for fixes. Can you confirm what you want to happen to here?

**Comment by chtof** [comment] 2020-01-28 11:57
@pauby My record of attempts... I haven't find a way to download the software by a script and don't understand the "logic" of the downloading platform. Need help or another maintainer (or maybe it's not possible to create a package).

**Comment by pauby** [comment] 2020-01-28 14:18
@chtof What's the issue? Maybe somebody can help?

**Comment by chtof** [comment] 2020-01-28 21:32
@pauby The issue is to find the URL to use. The last attempt was:
`packageName = $env:ChocolateyPackageName url = Get-RedirectedUrl 'http://file2.softsea.com/get.php?id=836900551' 'http://www.softsea.com/download/DjVu-Converter.html'`

It's difficult to explain. It works after you visit the website for a while. Maybe the access is allowed for a while but I don't know why. I have also tried another ways without success. Maybe it will clearer if you tell me which url you think I should use, I will submit the change and you will see the result. I repeat, I already spent a lot of time on this package. If you use developer tools, you will see several url are called (redirects). I don't know if we can use ie commands in a chocolateyinstall script as we can do in an update script as it's the only way I didn't try (maybe issue is due to javascript in the redirect page to the installer).
You can become crazy with this package because as I said it can work only for a while. You have been warned ;-)

**Comment by pauby** [comment] 2020-01-29 10:41
@gep13 has had some luck with working on the Package Validator recently due to similar hoops that need to be jumped through. Maybe he can help?

**Comment by pauby** [comment] 2020-02-07 09:25
@chtof Can you update us on this?

**Comment by chtof** [comment] 2020-02-07 19:40
@pauby The issue is to find the URL to use. The last attempt was:
url = Get-RedirectedUrl 'http://file2.softsea.com/get.php?id=836900551' 'http://www.softsea.com/download/DjVu-Converter.html'

It's difficult to explain. It works after you visit the website for a while. Maybe the access is allowed for a while but I don't know why. I have also tried another ways without success. Maybe it will clearer if you tell me which url you think I should use, I will submit the change and you will see the result. I repeat, I already spent a lot of time on this package. If you use developer tools, you will see several url are called (redirects). I don't know if we can use ie commands in a chocolateyinstall script as we can do in an update script as it's the only way I didn't try (maybe issue is due to javascript in the redirect page to the installer).
You can become crazy with this package because as I said it can work only for a while. You have been warned ;-)

**Comment by pauby** [comment] 2020-02-11 11:27
@chtof I saw that [original comment above](https://github.com/chocolatey-community/chocolatey-package-requests/issues/650#issuecomment-579466401).

[Have you reached out](https://github.com/chocolatey-community/chocolatey-package-requests/issues/650#issuecomment-579697208) to @gep13 or the vendor / author of the software to see if there is a direct link?

If you want to stop work on this just let me know and I'll update the labels. All I'm trying to do here is get this issue moving. I appreciate you've put a lot of work into it and it is appreciated.

**Comment by pauby** [comment] 2020-02-18 09:28
As this issue isn't making any traction (no fault of anybody on this thread) I propose closing it as 'Can't Implement' soon.

**Closed** 2020-03-09 12:03 UTC
Labels: Not Request / Can't Implement / Exists / Invalid
